### ISSUE TITLE
Ability to change hotkey

### ISSUE THREAD

**Issue by dabros** [Algalish/SmartFoundationsPublic#10]
I use fly mode (area actions) to redo my mega factories, LOVE this mod, would love to be able to change the hotkeys though (specifically alt in my own case) to avoid conflict.

Other mods might have global hotkeys too, so good idea in long run even outside that specific case.

If in-game is too hard, a config file would also work great.

Thanks

**Comment by Algalish** [comment]
@dabros  Yes, I will definitely do that once I take care of some urgent issues. But thats a complex task - many other mods lack this functionality.

**Comment by Algalish** [comment]
@dabros  Will it better for you if the hotkeys will "override" any existing hotkeys?
I mean if you are building a Smart Foundation and flying when you click Control you will not go down untill you confirm or exit the build. That can be easily done.

**Comment by dabros** [comment]
@Algalish - right now the conflict is with other mods hotkeys, so unsure if that would solve it there. 

I was also thinking changeable since similar comments on other mods regarding people using custom key layouts themselves, so would solve both other mods and alternate key layouts.

Though if you what you mean is you capture any "alt","space",ect keys in your mod in a way that stops them propogating/being detected Anywhere else (including other mods) - if that is reliable, then yeh thatll work, its just the unknown of other mods (not just standard keybindings)

**Comment by dabros** [comment]
One outside solution is offer multiple  keybindings, with those kept but additionally numpad keys (+-./*ect) - though might still run into same issues if not cause more... especially since your mostly ui free (which i love, so simple and easy)

Ive coded in C/++/# but no experience with unity so cant say best way to implement some time of override feature (i am a fan of external config if ui too hard)

**Comment by Algalish** [comment]
I added an alternative input with arrow keys insetad of Shift+MouseWheel or LeftAlt+MouseWheel. That should be enough for now.

**Comment by dabros** [comment]
@Algalish - thanks, ill try it out when i get home
