### ISSUE TITLE
Semi-Opaque Direction Indicator Arrow?

### ISSUE THREAD

**Issue by SextonKing** [Algalish/SmartFoundationsPublic#11]
Just a faint glowing red or green arrow superimposed over the hologram block would really help to more quickly see at a glance which direction the block is currently oriented in so I know if it’s established correctly. Right now the block looks nearly the same in any orientation so I often have to spend a few moments each time checking the orientation before I can activate a build.

**Comment by Algalish** [comment]
@SextonKing 
Does this arrow look OK to you?

![Screenshot_5](https://user-images.githubusercontent.com/1682176/97100427-94b0e280-16a4-11eb-879b-64de62df6539.png)

**Comment by SextonKing** [comment]
Yeah, that works fine. It looks better than my original suggestion actually, because your way the arrow can be seen clearly apart from the build hologram and won’t get lost in the flicker of the build image.

**Comment by Algalish** [comment]
@SextonKing  Implemented in V6
