### ISSUE TITLE
Unusable in Multiplayer - Causes client crash on foundation select

### ISSUE THREAD

**Issue by DanzaDragon** [Algalish/SmartFoundationsPublic#16]
Fantastic mod. Thank you so much for this! Although unusable for me in multiplayer! When hosting I can use the mod freely but clients crash when:

A foundation is selected from build menu
A foundation is eyedropped in game
A foundation is selected from the hotbar

The client can also have the mod when the host doesn't but that causes the same crash whenever they interact with foundations in any way.

Included is the crash log from client: 

Version: 131382, IsEditor: No, IsPerforceBuild: No, BuildConfiguration: Shipping, Launcher: Epic, NetMode: Client, IsUsingMods: Yes

Unhandled exception

UE4_SmartFoundations_Win64_Shipping
FactoryGame_Win64_Shipping!AActor::DispatchBeginPlay() [d:\ws\sb-200518130817-657\ue4\engine\source\runtime\engine\private\actor.cpp:3395]
FactoryGame_Win64_Shipping!AActor::PostNetInit() [d:\ws\sb-200518130817-657\ue4\engine\source\runtime\engine\private\actor.cpp:3360]
FactoryGame_Win64_Shipping!UActorChannel::ProcessBunch() [d:\ws\sb-200518130817-657\ue4\engine\source\runtime\engine\private\datachannel.cpp:2599]
FactoryGame_Win64_Shipping!UActorChannel::ReceivedBunch() [d:\ws\sb-200518130817-657\ue4\engine\source\runtime\engine\private\datachannel.cpp:2408]
FactoryGame_Win64_Shipping!UChannel::ReceivedNextBunch() [d:\ws\sb-200518130817-657\ue4\engine\source\runtime\engine\private\datachannel.cpp:775]
FactoryGame_Win64_Shipping!UChannel::ReceivedRawBunch() [d:\ws\sb-200518130817-657\ue4\engine\source\runtime\engine\private\datachannel.cpp:456]
FactoryGame_Win64_Shipping!UNetConnection::ReceivedPacket() [d:\ws\sb-200518130817-657\ue4\engine\source\runtime\engine\private\netconnection.cpp:2011]
FactoryGame_Win64_Shipping!UNetConnection::ReceivedRawPacket() [d:\ws\sb-200518130817-657\ue4\engine\source\runtime\engine\private\netconnection.cpp:1111]
FactoryGame_Win64_Shipping!UIpNetDriver::TickDispatch() [d:\ws\sb-200518130817-657\ue4\engine\plugins\online\onlinesubsystemutils\source\onlinesubsystemutils\private\ipnetdriver.cpp:564]
FactoryGame_Win64_Shipping!TBaseUObjectMethodDelegateInstance<0,AFGCharacterPlayer,void __cdecl(float)>::ExecuteIfSafe() [d:\ws\sb-200518130817-657\ue4\engine\source\runtime\core\public\delegates\delegateinstancesimpl.h:679]
FactoryGame_Win64_Shipping!TBaseMulticastDelegate<void,float>::Broadcast() [d:\ws\sb-200518130817-657\ue4\engine\source\runtime\core\public\delegates\delegatesignatureimpl.inl:977]
FactoryGame_Win64_Shipping!UWorld::Tick() [d:\ws\sb-200518130817-657\ue4\engine\source\runtime\engine\private\leveltick.cpp:1448]
FactoryGame_Win64_Shipping!UGameEngine::Tick() [d:\ws\sb-200518130817-657\ue4\engine\source\runtime\engine\private\gameengine.cpp:1366]
FactoryGame_Win64_Shipping!UFGGameEngine::Tick() [d:\ws\sb-200518130817-657\ue4\games\factorygame\source\factorygame\private\fggameengine.cpp:9]
FactoryGame_Win64_Shipping!FEngineLoop::Tick() [d:\ws\sb-200518130817-657\ue4\engine\source\runtime\launch\private\launchengineloop.cpp:4032]
FactoryGame_Win64_Shipping!GuardedMain() [d:\ws\sb-200518130817-657\ue4\engine\source\runtime\launch\private\launch.cpp:168]
FactoryGame_Win64_Shipping!GuardedMainWrapper() [d:\ws\sb-200518130817-657\ue4\engine\source\runtime\launch\private\windows\launchwindows.cpp:145]
FactoryGame_Win64_Shipping!WinMain() [d:\ws\sb-200518130817-657\ue4\engine\source\runtime\launch\private\windows\launchwindows.cpp:275]
FactoryGame_Win64_Shipping!__scrt_common_main_seh() [d:\agent\_work\2\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288]
kernel32
ntdll

Hope this helps squash any bugs! Thanks :)

**Comment by Algalish** [comment]
@DanzaDragon  Thank you for your kind words!!

I fixed this bug today already but haven't uploaded the update yet. 
Can I ask you to confirm that the problems is fixed before I release it? Here is the updated version.

Just reaname the file from .zip to .smod and you can use it and put it into your gam's mods folder.
[Smart_Foundations-0.4.2.zip](https://github.com/Algalish/SmartFoundationsPublic/files/5392809/Smart_Foundations-0.4.2.zip)

Let me know if that solved the problem.


P.S.This bug was not noted by me originally because in order to get it - you need to be in 2 distant places and not near each other. And there is no crash when you are seing each other  with another player.

**Comment by DanzaDragon** [comment]
I can confirm that it now works for us! Thanks for the fast response 👍 

We were 400 blocks apart this time and it worked just fine for both of us with no crashing!

**Comment by Algalish** [comment]
updated in 0.5.0
