### ISSUE TITLE
Add ability to use arrow keys to extend foundations

### ISSUE THREAD

**Issue by ngppgn** [Algalish/SmartFoundationsPublic#18]
Since the alt key is used in other mods, but the arrow keys seem pretty much unused, it might be interesting to enable them as an alternative way to shring/enlarge foundations. e.g. "up" enlarges and "down" shrinks along x axis while "left" enlarges and "right" shrinks along y axis.

**Comment by Algalish** [comment]
@ngppgn  done in 0.5.0

**Comment by zzubnik** [comment]
This makes the mod mostly useless for left-handed people who use the arrow keys to move around. Is there a solution for left-handed people? I know we are only 14 percent of the population, but it would be great if there was a left-handed mode where it used WASD instead for foundation changes.

**Comment by Algalish** [comment]
@zzubnik  just noticed your reply, because it was no the closed issue.
yes, there is an alternative controls for left handed people, you can turn it on in mod's settings
