### ISSUE TITLE
Smart Foundations can clip through things where Dumb Foundations can't

### ISSUE THREAD

**Issue by Rosuav** [Algalish/SmartFoundationsPublic#20]
If there's a building below you that extends up into the level you're on, you can't build normal foundations:
![Screenshot20201020-06070100000](https://user-images.githubusercontent.com/640535/96500738-08b14c00-129b-11eb-9515-c6fa5dcdc09b.png)

But you can use this mod to build foundations right through there - as long as you start somewhere that's legal:
![Screenshot20201020-06071400000](https://user-images.githubusercontent.com/640535/96500746-0a7b0f80-129b-11eb-9f45-9a116ee073cd.png)

It just happily clips right through.
![Screenshot20201020-06063000000](https://user-images.githubusercontent.com/640535/96500754-0ea72d00-129b-11eb-8525-5774b7b26b0a.png)

**Comment by Rosuav** [comment]
Also, that sticking-up thing is TOTALLY a tripping hazard. For the sake of the Engineer's safety, we must not let this happen! Kappa

**Comment by Algalish** [comment]
@Rosuav  You are absoulutely right. Since the mod was just an experiment in the beginning Ficsit Safety Department allowed us to do so but this is got to end now.

The mod is suppose to be non-intrusive and non-cheating so if someone wants to overlap things or build inside oher things... well.. they should not be allowed to do so.

Will be fixed in the new update.

**Comment by Rosuav** [comment]
Thank you. Your efforts will be noted in the Trans-Universal Engineer Safety Delegation Activists Yearly; the day that the engineer tripped and fell to her death was a defining moment in her career, but for the author of the mod, it was TUESDAY.

**Comment by Algalish** [comment]
@Rosuav  This is done in V6

**Comment by Rosuav** [comment]
Can confirm, it is no longer possible to build foundations through one's HUB. This is a great boon to the HUB-dwelling insects of Massage-Whatever-This-Planet-Is, as they no longer need fear having concrete magically inserted through their carefully-constructed homes. On their behalf, and on behalf of all sane people in the world, I thank you.

(I can represent sane people without being one, right?)
