### ISSUE TITLE
Numbers. [Number of fandations and ramps for exemple. No video, sorry:(.]

### ISSUE THREAD

**Issue by Jumbo-storm** [Algalish/SmartFoundationsPublic#35]
Featrue/Suggestion/QOL:
Can you add a feature so you can see how many platforms or ramps you have built, for example.

Why there is no video, (not (equally) important):
(I'm on the wrong computer. That's why I did not upload any video.
(I can not even record a video for OBS Studios screen turns black, so you will hear me but not see anything.)
That's why I did not upload any video.)

**Comment by Jumbo-storm** [comment]
Video is coming soon TM.

(Video is coming next next week. Or on next weeks friday or later. It depends on whether I remember it or not.)

**Comment by Tumblerino** [comment]
I actually sendt you a message on discord so i could help you out by donating towards to mod, since its LITERALLY UNPLAYABLE without smart foundations anymore.

**Comment by Algalish** [comment]
> I actually sendt you a message on discord so i could help you out by donating towards to mod, since its LITERALLY UNPLAYABLE without smart foundations anymore.

Hmm, no new messages for me. Can you send it again:   Algalish#1046  ?

**Comment by Algalish** [comment]
@Jumbo-storm  @Tumblerino  This is done in V.8
