### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by yBO-sentix** [Algalish/SmartFoundationsPublic#36]
Since the last Update the mod doesn't work at all anymore in my case. I can rotate the tiles but i can't place more then one at the same time

**Comment by Algalish** [comment]
hey @yBO-sentix . I am more then certain that this is bacause you are using the latest version of Smart Foundation but not using the latest version of the game (from experimental,  the pipes update).  I wrote a message about it in mod description but maybe you missed it.  you need to use version 0.6.0 and not 0.6.2 and it will work for you.

**Comment by yBO-sentix** [comment]
this will could be the thing, because i don't use the experimental version. Thank you for your information, i will try
