### ISSUE TITLE
Unable to launch

### ISSUE THREAD

**Issue by AdastormVproI7** [Algalish/SmartFoundationsPublic#37]
I am unable to launch the mod on version 0.3.6.

**Comment by Algalish** [comment]
Hey @AdastormVproI7 ! What problem are you experiencing with the mod? Are you using Steam or Epic games version of the game?  Are you using version 0.6.2 of the mod?

**Comment by AdastormVproI7** [comment]
Thanks for the quick reply! I'm using steam (not the experimental build), and the 0.6.2 version of the mod. Whenever I try and launch with the mod installed, it crashes, pulls up the unreal crash response window, and then reopens the game, but with no mod.

**Comment by Algalish** [comment]
Ah, you are using a non-experimental build. You need to use version 0.6.0 of the mod for now. I also mentioned that in the mod update description with big letters. But you are not the first to ask about it - about 30 people already did that. So in the next update I will be adding this nice popup at game start for users that will be installing next version on non-experimental version of the game.
Too many people asked for experimental support and it is impossible to support both versions at that point.
Let me know if that information helped you.


![Screenshot_13](https://user-images.githubusercontent.com/1682176/97834459-f991bb80-1ce8-11eb-906f-f0e9079eaf8b.png)
![Screenshot_14](https://user-images.githubusercontent.com/1682176/97834462-fbf41580-1ce8-11eb-9a37-f63efbd35f86.png)

**Comment by AdastormVproI7** [comment]
Thank you so much!

**Comment by AdastormVproI7** [comment]
The reason it was so hard for me to understand is that when I used the SMM, it said that there were no previous version of the mod available

**Comment by Algalish** [comment]
@AdastormVproI7  Yea, several people reported that problem with SMM and I am not sure how they figured it out. For me previous versions are available so thats strange. btw: if you put the mod in the mods folder manually and then run the game from SMM: it can  overwrite the mod by itself

**Comment by Algalish** [comment]
experimental and early access have the same version now. closing the issue
