### ISSUE TITLE
Arrow direction not the same as building direction.

### ISSUE THREAD

**Issue by Kubrix** [Algalish/SmartFoundationsPublic#44]
See this video:  https://yadi.sk/i/tTat2FbefvVCXQ
Arrow point forwards, foundations build to the right

**Comment by Algalish** [comment]
Hi @Kubrix  I think that when snapping to other buildings the rotation did change by itself (yes, that happens sometimes) so it changed the direction.    I haven't seen any arrows after snapping but pretty sure that arrow is pointing to the right now.

**Comment by Algalish** [comment]
I think my explanation above solves the issue so I am closing it
