### ISSUE TITLE
Add SmartWalls

### ISSUE THREAD

**Issue by Algalish** [Algalish/SmartFoundationsPublic#8]
A feature requested by **Rom1**.

**Comment by duppypro** [comment]
+1. This is super useful and intuitive, doesn't unbalance the game.
Please add walls, windows, fences, pillars, conveyer and hypertube poles. I even wish I had it for storage containers, constructors, assemblers, foundries. What wouldn't you want to build smart with?

**Comment by Algalish** [comment]
@duppypro  
Well said! What woudn't indeed.
There are many famous mods that allow you to do cool stuff. But even for myself its hard to understand all the tricks in them.  So the idea of Smart Foundations mod was  to build Smart but do it without thinking much - as you said : to make it intuitive. And quick too, without entering all the options.

I have big plans for all the things that you mentioned but it will take some time to finish all of that.
But an update with Smart Walls should be released very soon btw

**Comment by Algalish** [comment]
done in 0.5.0

**Comment by Algalish** [comment]
Juju from Youtube said that walls are not working in MP. Will investigate this.

**Comment by Algalish** [comment]
fixed for MP
